name: dfa_media
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  dart_mappable: ^2.0.3
  auto_route: ^5.0.1
  shimmer: ^3.0.0
  elementary: ^3.0.0
  chopper: ^7.0.8

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  chopper_generator:
  json_serializable:
  auto_route_generator:
  dart_mappable_builder: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/system/

